module \$__RAM_1024x32_1RW_ (...);

    localparam WIDTH = 32;
    localparam ABITS = 10;

    input  PORT_A_CLK;
    input  PORT_A_CLK_EN;
    input  [WIDTH-1:0] PORT_A_WR_DATA;
    input  [ABITS-1:0] PORT_A_ADDR;
    input  PORT_A_WR_EN;
    input  [WIDTH-1:0] PORT_A_WR_BE;
    output [WIDTH-1:0] PORT_A_RD_DATA;
    input  PORT_A_RD_EN;

    IHP_SRAM_1024x32_1RW _TECHMAP_REPLACE_ (
        // Port A - Write
        .CLK    (PORT_A_CLK),
        .ADDR0  (PORT_A_ADDR[0]),
        .ADDR1  (PORT_A_ADDR[1]),
        .ADDR2  (PORT_A_ADDR[2]),
        .ADDR3  (PORT_A_ADDR[3]),
        .ADDR4  (PORT_A_ADDR[4]),
        .ADDR5  (PORT_A_ADDR[5]),
        .ADDR6  (PORT_A_ADDR[6]),
        .ADDR7  (PORT_A_ADDR[7]),
        .ADDR8  (PORT_A_ADDR[8]),
        .ADDR9  (PORT_A_ADDR[9]),
        .DIN0   (PORT_A_WR_DATA[0]),
        .DIN1   (PORT_A_WR_DATA[1]),
        .DIN2   (PORT_A_WR_DATA[2]),
        .DIN3   (PORT_A_WR_DATA[3]),
        .DIN4   (PORT_A_WR_DATA[4]),
        .DIN5   (PORT_A_WR_DATA[5]),
        .DIN6   (PORT_A_WR_DATA[6]),
        .DIN7   (PORT_A_WR_DATA[7]),
        .DIN8   (PORT_A_WR_DATA[8]),
        .DIN9   (PORT_A_WR_DATA[9]),
        .DIN10   (PORT_A_WR_DATA[10]),
        .DIN11   (PORT_A_WR_DATA[11]),
        .DIN12   (PORT_A_WR_DATA[12]),
        .DIN13   (PORT_A_WR_DATA[13]),
        .DIN14   (PORT_A_WR_DATA[14]),
        .DIN15   (PORT_A_WR_DATA[15]),
        .DIN16   (PORT_A_WR_DATA[16]),
        .DIN17   (PORT_A_WR_DATA[17]),
        .DIN18   (PORT_A_WR_DATA[18]),
        .DIN19   (PORT_A_WR_DATA[19]),
        .DIN20   (PORT_A_WR_DATA[20]),
        .DIN21   (PORT_A_WR_DATA[21]),
        .DIN22   (PORT_A_WR_DATA[22]),
        .DIN23   (PORT_A_WR_DATA[23]),
        .DIN24   (PORT_A_WR_DATA[24]),
        .DIN25   (PORT_A_WR_DATA[25]),
        .DIN26   (PORT_A_WR_DATA[26]),
        .DIN27   (PORT_A_WR_DATA[27]),
        .DIN28   (PORT_A_WR_DATA[28]),
        .DIN29   (PORT_A_WR_DATA[29]),
        .DIN30   (PORT_A_WR_DATA[30]),
        .DIN31   (PORT_A_WR_DATA[31]),
        .BM0    (PORT_A_WR_BE[0]),
        .BM1    (PORT_A_WR_BE[1]),
        .BM2    (PORT_A_WR_BE[2]),
        .BM3    (PORT_A_WR_BE[3]),
        .BM4    (PORT_A_WR_BE[4]),
        .BM5    (PORT_A_WR_BE[5]),
        .BM6    (PORT_A_WR_BE[6]),
        .BM7    (PORT_A_WR_BE[7]),
        .BM8    (PORT_A_WR_BE[8]),
        .BM9    (PORT_A_WR_BE[9]),
        .BM10    (PORT_A_WR_BE[10]),
        .BM11    (PORT_A_WR_BE[11]),
        .BM12    (PORT_A_WR_BE[12]),
        .BM13    (PORT_A_WR_BE[13]),
        .BM14    (PORT_A_WR_BE[14]),
        .BM15    (PORT_A_WR_BE[15]),
        .BM16    (PORT_A_WR_BE[16]),
        .BM17    (PORT_A_WR_BE[17]),
        .BM18    (PORT_A_WR_BE[18]),
        .BM19    (PORT_A_WR_BE[19]),
        .BM20    (PORT_A_WR_BE[20]),
        .BM21    (PORT_A_WR_BE[21]),
        .BM22    (PORT_A_WR_BE[22]),
        .BM23    (PORT_A_WR_BE[23]),
        .BM24    (PORT_A_WR_BE[24]),
        .BM25    (PORT_A_WR_BE[25]),
        .BM26    (PORT_A_WR_BE[26]),
        .BM27    (PORT_A_WR_BE[27]),
        .BM28    (PORT_A_WR_BE[28]),
        .BM29    (PORT_A_WR_BE[29]),
        .BM30    (PORT_A_WR_BE[30]),
        .BM31    (PORT_A_WR_BE[31]),
        .WEN    (PORT_A_WR_EN),
        .REN    (PORT_A_RD_EN),
        .MEN    (PORT_A_CLK_EN),
        .DOUT0  (PORT_A_RD_DATA[0]),
        .DOUT1  (PORT_A_RD_DATA[1]),
        .DOUT2  (PORT_A_RD_DATA[2]),
        .DOUT3  (PORT_A_RD_DATA[3]),
        .DOUT4  (PORT_A_RD_DATA[4]),
        .DOUT5  (PORT_A_RD_DATA[5]),
        .DOUT6  (PORT_A_RD_DATA[6]),
        .DOUT7  (PORT_A_RD_DATA[7]),
        .DOUT8  (PORT_A_RD_DATA[8]),
        .DOUT9  (PORT_A_RD_DATA[9]),
        .DOUT10  (PORT_A_RD_DATA[10]),
        .DOUT11  (PORT_A_RD_DATA[11]),
        .DOUT12  (PORT_A_RD_DATA[12]),
        .DOUT13  (PORT_A_RD_DATA[13]),
        .DOUT14  (PORT_A_RD_DATA[14]),
        .DOUT15  (PORT_A_RD_DATA[15]),
        .DOUT16  (PORT_A_RD_DATA[16]),
        .DOUT17  (PORT_A_RD_DATA[17]),
        .DOUT18  (PORT_A_RD_DATA[18]),
        .DOUT19  (PORT_A_RD_DATA[19]),
        .DOUT20  (PORT_A_RD_DATA[20]),
        .DOUT21  (PORT_A_RD_DATA[21]),
        .DOUT22  (PORT_A_RD_DATA[22]),
        .DOUT23  (PORT_A_RD_DATA[23]),
        .DOUT24  (PORT_A_RD_DATA[24]),
        .DOUT25  (PORT_A_RD_DATA[25]),
        .DOUT26  (PORT_A_RD_DATA[26]),
        .DOUT27  (PORT_A_RD_DATA[27]),
        .DOUT28  (PORT_A_RD_DATA[28]),
        .DOUT29  (PORT_A_RD_DATA[29]),
        .DOUT30  (PORT_A_RD_DATA[30]),
        .DOUT31  (PORT_A_RD_DATA[31])
    );

endmodule
