meta:
  version: 2
  flow: FABulousTile

FABULOUS_TILE_DIR: dir::. #tiles/W_IO

# Basics
DESIGN_NAME: W_IO
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v
FABULOUS_EXTERNAL_SIDE: W

# Clock
#CLOCK_PERIOD: 20
#CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::sky130*:
    # High density cells
    # Width should be multiple of 0.46 (met2 pitch)
    # Height should be multiple of 0.68 (met3 pitch)
    # Standard cell row height: 2.72 (4 met3 track)
    DIE_AREA: [0, 0, 56.12, 223.04]
pdk::gf180mcu*:
    # Width should be multiple of 0.56 (Metal2 pitch)
    # Height should be multiple of 0.56 (Metal3 pitch)
    # Standard cell row height: 3.92 (8 Metal3 track)
    DIE_AREA: [0, 0, 72.80, 302.96]
pdk::ihp-sg13g2:
    # Width should be multiple of 0.48 (Metal2 pitch)
    # Height should be multiple of 0.42 (Metal3 pitch)
    # Standard cell row height: 3.78 (9 Metal3 tracks)
    DIE_AREA: [0, 0, 68.64, 219.24]
