meta:
  version: 2
  flow: FABulousTile

FABULOUS_TILE_DIR: dir::.

# Basics
DESIGN_NAME: S_term_single
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: N_GBUF_END[0]

# Area
FP_SIZING: absolute
pdk::sky130*:
    # High density cells
    # Width should be multiple of 0.46 (met2 pitch)
    # Height should be multiple of 0.68 (met3 pitch)
    # Standard cell row height: 2.72 (4 met3 track)
    DIE_AREA: [0, 0, 210.8, 57.12]
    PL_TARGET_DENSITY_PCT: 58
pdk::gf180mcu*:
    # Width should be multiple of 0.56 (Metal2 pitch)
    # Height should be multiple of 0.56 (Metal3 pitch)
    # Standard cell row height: 3.92 (8 Metal3 track)
    DIE_AREA: [0, 0, 302.96, 73.92]
    PL_TARGET_DENSITY_PCT: 85
pdk::ihp-sg13*:
    # Width should be multiple of 0.48 (Metal2 pitch)
    # Height should be multiple of 0.42 (Metal3 pitch)
    # Standard cell row height: 3.78 (9 Metal3 tracks)
    DIE_AREA: [0, 0, 219.84, 56.70]
    PL_TARGET_DENSITY_PCT: 96
